language: shell
os: linux
dist: xenial

services:
- docker

before_install:
- sudo apt update -y
- sudo apt install --only-upgrade docker-ce -y
- echo '{"experimental":true}' | sudo tee /etc/docker/daemon.json
- sudo service docker restart
- mkdir ~/.docker
- echo '{"experimental":"enabled"}' | tee ~/.docker/config.json
- docker info
- echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USERNAME}" --password-stdin;

jobs:
  include:
    - stage: "Build and publish alpine-glibc"
      env:
        - PROJECT_NAME=alpine-glibc
      script: .travis/build.sh
      deploy:
        - provider: script
          script: .travis/deploy.sh
    - stage: "Build and publish alpine-corretto-11"
      env:
        - PROJECT_NAME=alpine-corretto-11
      script: .travis/build.sh
      deploy:
        - provider: script
          script: .travis/deploy.sh
    - stage: "Build and publish alpine-maven"
      env:
        - PROJECT_NAME=alpine-maven
      script: .travis/build.sh
      deploy:
        - provider: script
          script: .travis/deploy.sh

# We want all PRs built but only merges on master branch
branches:
  only:
  - master

notifications:
  email:
    recipients:
      - ksclarke@ksclarke.io
    on_success: change
    on_failure: change
