language: shell
os: linux
dist: xenial

services:
- docker

before_install:
- sudo apt update -y
- sudo apt install --only-upgrade docker-ce -y
- docker info

jobs:
  include:
    - stage: "Build and publish alpine-glibc"
      env:
        - PROJECT_NAME=alpine-glibc
      script: alpine-glibc/build.sh
      deploy:
        - provider: script
          script: .travis/deploy.sh
    - stage: "Build and publish alpine-corretto-11"
      env:
        - REGISTRY_OWNER=$DOCKER_USERNAME
        - PROJECT_NAME=alpine-corretto-11
      script: alpine-corretto-11/build.sh
      deploy:
        - provider: script
          script: .travis/deploy.sh

# We want all PRs built but only merges on master branch
branches:
  only:
  - master

notifications:
  email:
    recipients:
      - ksclarke@ksclarke.io
    on_success: change
    on_failure: change
